-- Generated by execution/homework_sql.ts from docs/homework-2026-27/final/umm-al-kitab-2.json:
-- Umm al-Kitab 2 (Al-Isti'adhah), the remake after the content review. Week 2:
-- its video has been open since Thursday 8 October with no homework behind it.
-- Loads homework 202 for 2026/27. Review, then apply with execution/apply_migration.ts.
-- Idempotent: re-running replaces the same papers again.

do $guard$ begin
  if exists (select 1 from submissions s join homeworks h on h.id = s.homework_id
             join auth.users u on u.id = s.student_id
             where h.number in (202) and coalesce(u.email, '') not like '%@bsms-demo.test') then
    raise exception 'a real student has work on a homework this load replaces; stop and ask';
  end if;
end $guard$;

-- Demo work on the replaced papers (answers, voice notes, attempts cascade).
delete from submissions where homework_id in (select id from homeworks where number in (202));
delete from questions where homework_id in (select id from homeworks where number in (202));

-- ── Homework 202: Al-Istiʿādhah (9 marks, 8 questions)
insert into homeworks (number, title, series, total_marks, is_graded, week_id, due_at, course_id, ordinal)
select 202, $q$Al-Istiʿādhah$q$, 'umm_al_kitab', 9, true, w.id, w.due_at, c.id, 2
  from weeks w, courses c where w.term_id = 1 and w.number = 2 and c.key = 'ummul_kitab'
on conflict (number) do update set title = excluded.title, series = excluded.series, total_marks = excluded.total_marks,
  is_graded = true, course_id = excluded.course_id, ordinal = excluded.ordinal;
insert into questions (homework_id, position, qtype, scoring, prompt, points, is_bonus, is_task, options, rubric, needs_key)
select id, 1, 'text', 'exact', $q$The command to seek refuge before reciting comes from: "فَإِذَا قَرَأْتَ ٱلْقُرْءَانَ فَٱسْتَعِذْ بِٱللَّهِ مِنَ ٱلشَّيْطَـٰنِ ٱلرَّجِيمِ". What two things should you intend when saying the istiʿādhah?$q$, 2, false, false, null, $q$[{"id":"c1","desc":"Asking Allah to remove Shayṭān's whispers and doubts","marks":1},{"id":"c2","desc":"Asking Allah to keep you sincere and free of mistakes","marks":1}]$q$::jsonb, false
  from homeworks where number = 202;
insert into questions (homework_id, position, qtype, scoring, prompt, points, is_bonus, is_task, options, rubric, needs_key)
select id, 2, 'checkbox', 'exact', $q$When should the istiʿādhah be said out loud?$q$, 1, false, false, $q$[{"position":0,"label":"Option A","value":"Someone is listening to you","correct":true},{"position":1,"label":"Option B","value":"You are the first to recite in a group","correct":true},{"position":2,"label":"Option C","value":"You are praying","correct":false},{"position":3,"label":"Option D","value":"You are reciting alone","correct":false},{"position":4,"label":"Option E","value":"You are in a group but not the first to recite","correct":false}]$q$::jsonb, null, false
  from homeworks where number = 202;
insert into questions (homework_id, position, qtype, scoring, prompt, points, is_bonus, is_task, options, rubric, needs_key)
select id, 3, 'checkbox', 'exact', $q$You stop reciting partway through. In which cases must you say the istiʿādhah again before continuing?$q$, 2, false, false, $q$[{"position":0,"label":"Option A","value":"To answer a phone call","correct":true},{"position":1,"label":"Option B","value":"Someone distracts you with an unrelated conversation","correct":true},{"position":2,"label":"Option C","value":"You cough or sneeze","correct":false},{"position":3,"label":"Option D","value":"You pause to reflect on a verse","correct":false},{"position":4,"label":"Option E","value":"Your teacher stops you to give feedback","correct":false}]$q$::jsonb, null, false
  from homeworks where number = 202;
insert into questions (homework_id, position, qtype, scoring, prompt, points, is_bonus, is_task, options, rubric, needs_key)
select id, 4, 'mcq', 'exact', $q$The hamzah at the start of أَعُوذُ sounds like the "a" in…$q$, 1, false, false, $q$[{"position":0,"label":"Option A","value":"anyway","correct":true},{"position":1,"label":"Option B","value":"umbrella","correct":false}]$q$::jsonb, null, false
  from homeworks where number = 202;
insert into questions (homework_id, position, qtype, scoring, prompt, points, is_bonus, is_task, options, rubric, needs_key)
select id, 5, 'mcq', 'exact', $q$The ذ in أَعُوذُ is pronounced as…$q$, 1, false, false, $q$[{"position":0,"label":"Option A","value":"ذ (\"th\" as in \"this\")","correct":true},{"position":1,"label":"Option B","value":"د","correct":false},{"position":2,"label":"Option C","value":"ز","correct":false}]$q$::jsonb, null, false
  from homeworks where number = 202;
insert into questions (homework_id, position, qtype, scoring, prompt, points, is_bonus, is_task, options, rubric, needs_key)
select id, 6, 'mcq', 'exact', $q$The ج in ٱلرَّجِيمِ sounds like…$q$, 1, false, false, $q$[{"position":0,"label":"Option A","value":"the \"j\" in \"jug\"","correct":true},{"position":1,"label":"Option B","value":"the French \"j\" in \"bonjour\"","correct":false},{"position":2,"label":"Option C","value":"the \"g\" in \"go\"","correct":false}]$q$::jsonb, null, false
  from homeworks where number = 202;
insert into questions (homework_id, position, qtype, scoring, prompt, points, is_bonus, is_task, options, rubric, needs_key)
select id, 7, 'mcq', 'exact', $q$True or false: the nūn of مِنَ becomes heavy because it is followed by ٱلشَّيْطَـٰنِ.$q$, 1, false, false, $q$[{"position":0,"label":"Option A","value":"True","correct":false},{"position":1,"label":"Option B","value":"False","correct":true}]$q$::jsonb, null, false
  from homeworks where number = 202;
insert into questions (homework_id, position, qtype, scoring, prompt, points, is_bonus, is_task, options, rubric, needs_key)
select id, 8, 'text', 'manual', $q$Practical task: record yourself here saying the istiʿādhah three times, slowly, then once more at your normal pace.$q$, 0, false, true, null, null, false
  from homeworks where number = 202;

select number, title, total_marks, (select count(*) from questions q where q.homework_id = h.id) as questions
  from homeworks h where number in (202) order by number;
