-- Generated by execution/homework_sql.ts from docs/homework-2026-27/final/qaidah-hw2.json:
-- Qaidah homework 2 (joined letters, Lesson 2) for Masjid Al-Aqsa, from Moadh's doc of
-- 10 October: one recording in the app, reading out every box on the book's pages 7-8
-- and the last row, which the question carries as pictures (0081). Ungraded: nothing to
-- mark automatically; the teacher listens on the marking screen.
-- Loads homework 302 for 2026/27. Review, then apply with execution/apply_migration.ts.
-- Idempotent: re-running replaces the same papers again.

do $guard$ begin
  if exists (select 1 from submissions s join homeworks h on h.id = s.homework_id
             join auth.users u on u.id = s.student_id
             where h.number in (302) and coalesce(u.email, '') not like '%@bsms-demo.test') then
    raise exception 'a real student has work on a homework this load replaces; stop and ask';
  end if;
end $guard$;

-- Demo work on the replaced papers (answers, voice notes, attempts cascade).
delete from submissions where homework_id in (select id from homeworks where number in (302));
delete from questions where homework_id in (select id from homeworks where number in (302));

-- ── Homework 302: Joined Letters (Lesson 2) (0 marks, 1 questions)
insert into homeworks (number, title, series, total_marks, is_graded, week_id, due_at, course_id, ordinal)
select 302, $q$Joined Letters (Lesson 2)$q$, 'qaidah', 0, false, w.id, w.due_at, c.id, 2
  from weeks w, courses c where w.term_id = 1 and w.number = 2 and c.key = 'qaidah'
on conflict (number) do update set title = excluded.title, series = excluded.series, total_marks = excluded.total_marks,
  is_graded = false, course_id = excluded.course_id, ordinal = excluded.ordinal;
insert into questions (homework_id, position, qtype, scoring, prompt, points, is_bonus, is_task, options, rubric, needs_key)
select id, 1, 'text', 'manual', $q$Read out each box on these pages by naming every letter in it. For example, قفل is ق ف ل (Qaaf, Faa, Laam).
Practise it first so your recording is short and quick, then record yourself here.$q$, 0, false, true, null, null, false
  from homeworks where number = 302;

-- Audio needs questions.media (migration 0048); skipped until it exists.
do $media$ begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'questions' and column_name = 'media') then
    update questions set media = $q${"images":[{"src":"/images/homework/qaidah/hw2-1.jpg","alt":"Qāʿidah Lesson 2, joined letters: page 7","width":1219,"height":1400},{"src":"/images/homework/qaidah/hw2-2.jpg","alt":"Qāʿidah Lesson 2, joined letters: page 8","width":1207,"height":1400},{"src":"/images/homework/qaidah/hw2-3.jpg","alt":"Qāʿidah Lesson 2, joined letters: the last boxes","width":1400,"height":512}]}$q$::jsonb where position = 1 and homework_id = (select id from homeworks where number = 302);
  end if;
end $media$;

select number, title, total_marks, (select count(*) from questions q where q.homework_id = h.id) as questions
  from homeworks h where number in (302) order by number;
