#!/usr/bin/env python3
"""
Fetch surah introductions from the Quran.com API into a static TS module.

Why a script and not a runtime call:
  · the hifz page would otherwise depend on a third party being up
  · the text never changes, so fetching it per request is waste
  · it matches surah-meta.ts, which already stores ayah counts as static data

Run it when the memorisation range changes. It rewrites the whole file.

    python3 execution/fetch_surah_info.py

Output: web/src/lib/hifz/surah-info.ts

ATTRIBUTION. The prose is Sayyid Abul A'la Maududi's *Tafhim al-Qur'an*,
served by Quran.com. The `source` string comes back with every record and the
UI must display it — it is someone's scholarship, not free text.

Gotchas learned the hard way:
  · the API 403s on urllib's default User-Agent. Send a browser one.
  · `short_text` is only the "Name" section — where the surah's name comes
    from. The useful parts (Period of Revelation, Theme) are inside the HTML
    `text` field, under <h2> headings.
  · Al-Falaq and An-Nas share ONE introduction; the payload says so in a lead
    paragraph. Keep that note, or the text reads as though it has wandered
    off-topic onto the other surah.
"""

import html as H
import json
import re
import sys
import time
import urllib.request

API = "https://api.quran.com/api/v4"
UA = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
    ),
    "Accept": "application/json",
}

# The memorisation run, matching surah-meta.ts.
FIRST, LAST = 72, 114
OUT = "web/src/lib/hifz/surah-info.ts"


def get(url: str):
    req = urllib.request.Request(url, headers=UA)
    return json.load(urllib.request.urlopen(req, timeout=25))


def clean(s: str) -> str:
    return re.sub(r"\s+", " ", H.unescape(re.sub(r"<[^>]+>", " ", s))).strip()


def sections(markup: str):
    """Split the info HTML on its <h2> headings. Returns (lead, {heading: text})."""
    parts = re.split(r"<h2[^>]*>(.*?)</h2>", markup, flags=re.S | re.I)
    lead = clean(parts[0]) if parts else ""
    return lead, {clean(parts[i]): clean(parts[i + 1]) for i in range(1, len(parts) - 1, 2)}


def trim(text: str, limit: int = 520) -> str:
    """Cut to the last full sentence inside `limit`, rather than mid-word."""
    if len(text) <= limit:
        return text
    cut = text[:limit]
    stop = max(cut.rfind(". "), cut.rfind("? "), cut.rfind("! "))
    return cut[: stop + 1] if stop > 200 else cut.rstrip() + "…"


def main() -> int:
    rows = {}
    for n in range(FIRST, LAST + 1):
        try:
            ch = get(f"{API}/chapters/{n}?language=en")["chapter"]
            info = get(f"{API}/chapters/{n}/info?language=en").get("chapter_info", {})
            lead, sec = sections(info.get("text") or "")
            pick = lambda *keys: next(
                (v for k, v in sec.items() if any(w in k.lower() for w in keys)), ""
            )
            rows[n] = {
                "revealedIn": ch["revelation_place"],
                "revelationOrder": ch["revelation_order"],
                "revealed": trim(pick("period")),
                "theme": trim(pick("theme", "subject")),
                # Only kept when the payload says the introduction is shared.
                "sharedWith": clean(lead) if re.search(r"introduction is for both", lead, re.I) else "",
                "source": info.get("source", ""),
            }
            print(f"  {n:>3} {ch['name_simple']}")
            time.sleep(0.06)
        except Exception as e:  # noqa: BLE001 — one bad surah shouldn't lose the rest
            print(f"  {n:>3} FAILED: {e}", file=sys.stderr)

    if len(rows) < (LAST - FIRST + 1):
        print(f"\nOnly {len(rows)} of {LAST - FIRST + 1} fetched — not writing.", file=sys.stderr)
        return 1

    # "\n".join, not ",\n".join — each line already ends with its own comma.
    body = "\n".join(
        f"  {n}: {json.dumps(r, ensure_ascii=False)}," for n, r in sorted(rows.items())
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(
            "/* GENERATED by execution/fetch_surah_info.py — do not edit by hand.\n"
            " *\n"
            " * Surah introductions from the Quran.com API. The prose is Sayyid Abul\n"
            " * A'la Maududi's Tafhim al-Qur'an; `source` carries the attribution and\n"
            " * the UI is required to show it.\n"
            " *\n"
            " * `sharedWith` is set only where the source gives two surahs one joint\n"
            " * introduction (Al-Falaq and An-Nas, the Mu'awwidhatayn). Show it, or the\n"
            " * text reads as though it has wandered onto a different surah.\n"
            " */\n\n"
            "export type SurahInfo = {\n"
            "  revealedIn: string;\n"
            "  revelationOrder: number;\n"
            "  revealed: string;\n"
            "  theme: string;\n"
            "  sharedWith: string;\n"
            "  source: string;\n"
            "};\n\n"
            "export const SURAH_INFO: Record<number, SurahInfo> = {\n"
            f"{body[:-1]}\n"
            "};\n"
        )
    print(f"\nWrote {OUT} — {len(rows)} surahs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
