/** One word of the seeded Uthmani text, positioned in the Madani mushaf. */
export type QuranWord = {
  surah: number;
  ayah: number;
  position: number; // 1-based within the ayah
  text: string;
  glyph: string | null; // QCF v2 page-font character — the printed word itself
  isEnd: boolean;   // ayah-end marker (the numeral)
  page: number;
  line: number;
};

export type QuranWordRow = {
  surah_number: number;
  ayah_number: number;
  word_position: number;
  text_uthmani: string;
  code_v1: string | null;
  code_v2: string | null;
  is_end: boolean;
  page_number: number;
  line_number: number;
};

export type MushafLine = { line: number; words: QuranWord[] };
export type MushafPage = { page: number; lines: MushafLine[] };

export const wordKey = (w: Pick<QuranWord, "surah" | "ayah" | "position">): string =>
  `${w.surah}:${w.ayah}:${w.position}`;

/** A whole ayah — the key a mistake takes when it isn't pinned to one word.
 *  Two segments where wordKey has three, so the two can never collide. */
export const ayahKey = (w: Pick<QuranWord, "surah" | "ayah">): string =>
  `${w.surah}:${w.ayah}`;

/** The key a logged mistake lives under: the ayah when `position` is null
 *  (the reviewer tapped the ayah's end marker), the word otherwise. This is
 *  the single place that convention is decided — everything that stores or
 *  looks up a mark goes through it. */
export const markKey = (
  m: { surah: number; ayah: number; position: number | null },
): string => (m.position === null ? ayahKey(m) : wordKey({ ...m, position: m.position }));

// V1 (1405H) — the school's physical mushaf, confirmed by its own line
// breaks (Al-Ikhlas splits لم يلد / ولم يولد). Glyph edition must match
// the page fonts AND the seeded line data; never mix editions per word.
export const fromRow = (r: QuranWordRow): QuranWord => ({
  surah: r.surah_number, ayah: r.ayah_number, position: r.word_position,
  text: r.text_uthmani, glyph: r.code_v1, isEnd: r.is_end,
  page: r.page_number, line: r.line_number,
});

/**
 * Lines the print centres instead of stretching to the margins — closing
 * lines of surahs, mostly. This is quran.com's production table
 * (src/components/Verse/pageUtils.ts, QCF v1), trimmed to the pages the
 * app can render; the print itself is the authority it encodes.
 *
 * Audited against the seeded line numbering and the justification each line
 * actually receives. Two things a future reader should know:
 *
 *  - Four entries are INERT here: 586:1, 593:2 and 594:5 name lines that
 *    carry no words in our data (they fall on header/basmala slots), so
 *    they never fire. They are left as quran.com has them rather than
 *    invented away — but do not read this table as a list of what the
 *    print centres. It is only the part of that list we inherited.
 *  - 600 was 10, which is likewise a wordless slot. The line the print
 *    actually centres there is 9 — Al-Qari'ah's close — confirmed against
 *    the physical 1405 copy. Left justified it was the single worst line
 *    in the whole range, stretched 1.899em (13.1%); centred it sits with
 *    0.949em a side, about three quarters of an ayah marker, which is the
 *    small inset the print shows.
 *
 * Nothing else needs adding: across all 541 justified lines the median
 * stretch is 0.123em (0.8% of the measure) and the next worst is 4.2%.
 * Rerun execution/audit_mushaf_measure.py to re-derive those figures.
 */
const CENTER_ALIGNED_PAGE_LINES: Record<number, number[]> = {
  586: [1], 593: [2], 594: [5], 600: [9],
  602: [5, 15], 603: [10, 15], 604: [4, 9, 14, 15],
};

/** Should this printed line centre rather than fill the measure? */
export function isCenteredLine(page: number, line: number): boolean {
  return CENTER_ALIGNED_PAGE_LINES[page]?.includes(line) ?? false;
}

/**
 * page → the natural width of its widest line, in em of that page's own
 * QCF font. QCF v1 is one font per page and each is cut to its own
 * engraving, so this is NOT a constant: it runs from 14.25em (604) to
 * 15.55em (585). The reader needs it to stretch the surah band to the
 * width of the text block — one fixed stretch overshoots narrow pages.
 *
 * Generated by execution/audit_mushaf_measure.py — do not hand-edit;
 * rerun the script if the seed changes.
 */
export const PAGE_MEASURE: Record<number, number> = {
  562: 14.7163,
  563: 14.4624,
  564: 14.5640,
  565: 14.9707,
  566: 14.8413,
  567: 15.1924,
  568: 14.7554,
  569: 14.9028,
  570: 14.7476,
  571: 14.5566,
  572: 14.5552,
  573: 14.7085,
  574: 14.7144,
  575: 15.2139,
  576: 14.8960,
  577: 15.2041,
  578: 15.1514,
  579: 14.8760,
  580: 14.8286,
  581: 14.9331,
  582: 14.9878,
  583: 14.9229,
  584: 15.1680,
  585: 15.5493,
  586: 15.2017,
  587: 14.8223,
  588: 14.9692,
  589: 14.9546,
  590: 14.8315,
  591: 15.1265,
  592: 14.8154,
  593: 14.6865,
  594: 14.8384,
  595: 15.0142,
  596: 14.4136,
  597: 15.3438,
  598: 14.4780,
  599: 14.8687,
  600: 14.4502,
  601: 15.0952,
  602: 14.4033,
  603: 14.4756,
  604: 14.2480,
};

/** Fallback for a page outside the seeded range — the median measure. */
export const DEFAULT_MEASURE = 14.8413;

export type PageSlot =
  | { type: "words"; line: MushafLine }
  | { type: "header"; surah: number }
  | { type: "basmala" };

/**
 * Every printed page is EXACTLY 15 numbered lines. Word data only covers
 * lines that carry ayah words; the print reserves the gaps for surah
 * headers and basmalas — including a header whose surah's words only
 * begin on the NEXT page. Reconstruct the full 15 slots:
 *  - a gap run of 2 before a surah's opening words = header + basmala;
 *  - a single gap before them = basmala (its header closed the previous
 *    page);
 *  - trailing gaps after the page's last words belong to the next surah
 *    in mushaf order: header, then basmala.
 */
export function pageSlots(page: MushafPage): PageSlot[] {
  const byLine = new Map(page.lines.map((l) => [l.line, l]));
  const lastSurah = page.lines.at(-1)?.words.at(-1)?.surah ?? 0;
  const slots: PageSlot[] = [];
  for (let n = 1; n <= 15; n++) {
    const line = byLine.get(n);
    if (line) {
      slots.push({ type: "words", line });
      continue;
    }
    let next: MushafLine | undefined;
    for (let m = n + 1; m <= 15 && !next; m++) next = byLine.get(m);
    if (next) {
      const w = next.words[0];
      const opener = w.ayah === 1 && w.position === 1;
      let gapRun = 0;
      for (let m = n; m <= 15 && !byLine.get(m); m++) gapRun++;
      if (opener && gapRun >= 2) slots.push({ type: "header", surah: w.surah });
      else slots.push({ type: "basmala" });
    } else {
      const prev = slots[slots.length - 1];
      slots.push(
        prev?.type === "header" ? { type: "basmala" } : { type: "header", surah: lastSurah + 1 },
      );
    }
  }
  return slots;
}

/** DB order (ayah asc, position asc) IS mushaf reading order within a surah;
 *  grouping by consecutive page/line values reproduces the printed lines. */
export function groupIntoPages(words: QuranWord[]): MushafPage[] {
  const pages: MushafPage[] = [];
  for (const w of words) {
    let page = pages[pages.length - 1];
    if (!page || page.page !== w.page) {
      page = { page: w.page, lines: [] };
      pages.push(page);
    }
    let line = page.lines[page.lines.length - 1];
    if (!line || line.line !== w.line) {
      line = { line: w.line, words: [] };
      page.lines.push(line);
    }
    line.words.push(w);
  }
  return pages;
}
