/** Static mushaf facts for the surahs in the memorisation run (72–114).
 *  Not in the DB on purpose — this never changes. */
export const SURAH_META: Record<number, { ayahs: number; meaning: string }> = {
  72: { ayahs: 28, meaning: "The Jinn" },
  73: { ayahs: 20, meaning: "The Enshrouded One" },
  74: { ayahs: 56, meaning: "The Cloaked One" },
  75: { ayahs: 40, meaning: "The Resurrection" },
  76: { ayahs: 31, meaning: "Man" },
  77: { ayahs: 50, meaning: "Those Sent Forth" },
  78: { ayahs: 40, meaning: "The Great News" },
  79: { ayahs: 46, meaning: "Those Who Pull Out" },
  80: { ayahs: 42, meaning: "He Frowned" },
  81: { ayahs: 29, meaning: "The Folding Up" },
  82: { ayahs: 19, meaning: "The Cleaving" },
  83: { ayahs: 36, meaning: "Those Who Deal in Fraud" },
  84: { ayahs: 25, meaning: "The Splitting Asunder" },
  85: { ayahs: 22, meaning: "The Constellations" },
  86: { ayahs: 17, meaning: "The Night Comer" },
  87: { ayahs: 19, meaning: "The Most High" },
  88: { ayahs: 26, meaning: "The Overwhelming" },
  89: { ayahs: 30, meaning: "The Dawn" },
  90: { ayahs: 20, meaning: "The City" },
  91: { ayahs: 15, meaning: "The Sun" },
  92: { ayahs: 21, meaning: "The Night" },
  93: { ayahs: 11, meaning: "The Morning Brightness" },
  94: { ayahs: 8, meaning: "The Relief" },
  95: { ayahs: 8, meaning: "The Fig" },
  96: { ayahs: 19, meaning: "The Clot" },
  97: { ayahs: 5, meaning: "The Night of Decree" },
  98: { ayahs: 8, meaning: "The Clear Evidence" },
  99: { ayahs: 8, meaning: "The Earthquake" },
  100: { ayahs: 11, meaning: "The Chargers" },
  101: { ayahs: 11, meaning: "The Striking Hour" },
  102: { ayahs: 8, meaning: "Rivalry in Increase" },
  103: { ayahs: 3, meaning: "The Time" },
  104: { ayahs: 9, meaning: "The Slanderer" },
  105: { ayahs: 5, meaning: "The Elephant" },
  106: { ayahs: 4, meaning: "Quraysh" },
  107: { ayahs: 7, meaning: "Small Kindnesses" },
  108: { ayahs: 3, meaning: "Abundance" },
  109: { ayahs: 6, meaning: "The Disbelievers" },
  110: { ayahs: 3, meaning: "The Help" },
  111: { ayahs: 5, meaning: "The Palm Fibre" },
  112: { ayahs: 4, meaning: "The Sincerity" },
  113: { ayahs: 5, meaning: "The Daybreak" },
  114: { ayahs: 6, meaning: "Mankind" },
};
